name: Release

on:
  push:
    branches:
      - Main

env:
  ARTIFACT_PATH: release/
  ZIP_FILE_NAME: release.zip

jobs:
  create_release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
            node-version: '18'
            cache: 'npm'
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
            name: Release
            path: /dist

      - name: Get latest tag
        id: latest_tag
        shell: pwsh
        run: |
          $LATEST_TAG = git describe --tags --abbrev=0
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
            files: ${{ env.ARTIFACT_PATH }}*
            tag_name: ${{ steps.latest_tag.outputs.latest_tag }}
            name: Release ${{ steps.latest_tag.outputs.latest_tag }}
            generate_release_notes: true